module.exports = [
  {
    id: "1",
    imgSource: "/img/user.jpg",
    imgAlt: "Me",
    firstname: "Géraldine",
    lastname: "Dubois",
    email: "géraldine.dubois@live.fr",
    isApproved: true,
  },
  {
    id: "2",
    imgSource: "/img/user.jpg",
    imgAlt: "Me",
    firstname: "Sandie",
    lastname: "Dubois",
    isApproved: true,
  },
  {
    id: "3",
    imgSource: "/img/user.jpg",
    imgAlt: "Me",
    firstname: "Catherine",
    lastname: "Siciaux",
    isApproved: true,
  },
  {
    id: "4",
    imgSource: "/img/user.jpg",
    imgAlt: "Me",
    firstname: "Géraldine",
    lastname: "Dubois",
    isApproved: true,
  },
  {
    id: "5",
    imgSource: "/img/user.jpg",
    imgAlt: "Me",
    firstname: "Géraldine",
    lastname: "Dubois",
    isApproved: true,
  },
  {
    id: "6",
    imgSource: "/img/user.jpg",
    imgAlt: "Me",
    firstname: "Géraldine",
    lastname: "Dubois",
    isApproved: true,
  },
  {
    id: "7",
    imgSource: "/img/user.jpg",
    imgAlt: "Me",
    firstname: "Géraldine",
    lastname: "Dubois",
    isApproved: true,
  },
  {
    id: "8",
    imgSource: "/img/user.jpg",
    imgAlt: "Me",
    firstname: "Géraldine",
    lastname: "Dubois",
    isApproved: true,
  },
];
